# ===== Database =====
spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== Hotspot download =====
app.pull-interval=30000
app.base-url=https://dataserver-coids.inpe.br/queimadas/queimadas/focos/csv/10min/focos_10min_20250529_0000.csv
